apiVersion: v1
kind: Pod
metadata:
  name: workload-1
spec:
  containers:
  - name: example-workload
    image: spiffe-csi-driver-example-workload:example
    imagePullPolicy: Never
    volumeMounts:
    - name: spiffe-workload-api
      mountPath: /spiffe-workload-api
      readOnly: true
    env:
    - name: VAULT_ADDR
      value: http://10.128.0.62:8200
    - name: SPIFFE_ENDPOINT_SOCKET
      value: unix:///spiffe-workload-api/spire-agent.sock
  volumes:
  - name: spiffe-workload-api
    csi:
      driver: "csi.spiffe.io"
      readOnly: true
